In [2]:
import numpy as np
a=np.array([20,30,40])
b=np.array([60,70,80])
print(a)
print(b)
print(a+b)
print(a*b)

[20 30 40]
[60 70 80]
[ 80 100 120]
[1200 2100 3200]


In [3]:
import numpy as np
arr=np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print(arr)
print(type(arr))

[[10 20 30 40]
 [50 60 70 80]
 [20 40 60 80]]
<class 'numpy.ndarray'>


In [4]:
#slicing
import numpy as np
arr=np.array([10,20,30,40])
print(arr[0:3])
print(arr[:3])

[10 20 30]
[10 20 30]


In [5]:
#indexing in array
import numpy as np
arr=np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print(arr[0,1:3])
print(arr[2,2])

[20 30]
60


In [6]:
#attributes of array in numpy
import numpy as np
arr=np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

(3, 4)
12
2
int32


In [7]:
#inspecting an array
import numpy as np
a=[[30,40,40],[40,30,10]]
arr=np.array(a)
print(arr)
print(np.shape(arr))
print(len(arr))
print(np.size(arr))
print(type(arr))
print(arr.dtype)
print(arr.astype(float))

[[30 40 40]
 [40 30 10]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int32
[[30. 40. 40.]
 [40. 30. 10.]]


In [8]:
#mathematical operations on arrays
import numpy as np
arr1=np.array([30,40,50])
arr2=np.array([20,30,10])
print(arr1+arr2)
print(np.add(arr1,arr2))
print(arr1-arr2)
print(np.subtract(arr1,arr2))


[50 70 60]
[50 70 60]
[10 10 40]
[10 10 40]


In [9]:
#concatenate
import numpy as np
arr1=np.array([[30,40],[50,10]])
arr2=np.array([[20,30],[10,3]])
print(np.concatenate([arr1,arr2],axis=0))#horizontal axis
print(np.concatenate([arr1,arr2],axis=1))#vertical axis

[[30 40]
 [50 10]
 [20 30]
 [10  3]]
[[30 40 20 30]
 [50 10 10  3]]


In [10]:
print(np.hstack([arr1,arr2]))#horizontal concatenation
print(np.vstack([arr1,arr2]))#vertical concatenation

[[30 40 20 30]
 [50 10 10  3]]
[[30 40]
 [50 10]
 [20 30]
 [10  3]]


In [11]:
#splitting array
a=np.array([20,40,30,40,10,20])
b=np.array_split(a,5)
print(b)
print(b[1])

[array([20, 40]), array([30]), array([40]), array([10]), array([20])]
[30]


In [12]:
#append in array
import numpy as np
a=np.array([20,40,60,80])
print(np.append(a,90))

[20 40 60 80 90]


In [13]:
a=np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [14]:
#insert in array
a=np.array([20,40,60,80])
print(np.append(a,1,50))


[20 40 60 80  1]


In [15]:
a=np.array([[20,40],[60,80]])
print(np.insert(a,1,[50,60]))


[20 50 60 40 60 80]


In [16]:
#delete element in array
print(np.delete(a,1))

[20 60 80]


In [17]:
a=np.array([[20,40],[60,80]])
print(np.delete(a,1,axis=0))

[[20 40]]


In [19]:
#sort
ar=np.array([[7,8,4,12,9],[4,8,10,3,2]])
print(np.sort(ar))

[[ 4  7  8  9 12]
 [ 2  3  4  8 10]]


In [21]:
#search
ar=np.array([3,4,1,7,8])
s=np.where(ar%2==0)
print(s)

(array([1, 4], dtype=int64),)


In [23]:
#searchsorted
ar=np.array([1,2,3,4,5])
ss=np.searchsorted(ar,2)
print(ss)

1


In [26]:
#filter
ar=np.array([20,30,40,50])
fa=[True,False,True,False]
new=ar[fa]
print(new)


[20 40]


In [28]:
ar=np.array([20,30,40,50])
fa=ar>35
new=ar[fa]
print(new)

[40 50]


In [30]:
#aggregate functions in numpy
a=np.array([20,40,60,70])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

190
20
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [32]:
a=[100,150,199,200,250,130]
b=[10,50,30,40,30,10]
price=np.array(a)
quantity=np.array(b)
print(price,quantity)
print()
c=np.cumprod([price,quantity],axis=0)
print(c[1].sum())

[100 150 199 200 250 130] [10 50 30 40 30 10]

31270


In [36]:
#statistical functions
import statistics as stats
baked_food=[200,150,150,130,200,220,170,188]
a=np.array(baked_food)
print(np.mean(baked_food))
print(np.median(baked_food))
print(stats.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))

176.0
179.0
200
29.017236257093817
842.0


In [39]:
#-1 represents inversely proportional relationship
#1 reprsents proportional relationship
#0 means no relationship
import numpy as np
tobacco_consumption=[30,50,10,30,50,40]
deaths=[100,120,70,100,120,112]
print(np.corrcoeff([tobacco_consumption,deaths]))

AttributeError: module 'numpy' has no attribute 'corrcoeff'